travis:
  secure:
    BINSTAR_TOKEN: nprvt+T6UYPRsKBviFb2C+SJyyJhpqr+dhbwrEcsbluqD+LVLfq3dRsuuHJAzAht8Iz9n/3jxYGJoUj8l/FPiblE1dLPMtqltxDnX7AH9Q/mhZyResc9IH/AceSYxNj7Oc/HrxqHKZ3wT7g4e95lqS5tzd2f0h6nYphqFoFoKw+lWrZpguhhS6p4QKadshVgXod9HhDzjNbeZ5UorK5TvG/pScyJHUYqd19hPWwtQhiiXmFQDuXU+d5vpnB3LadgcPNBmp/lo6GEI5uTr7DYSCFskUxrMgye7zKf8guCdW+raPKLMy/4+tJT+98jouq2yr2+8MWtLu95t0v/vXMJ45AABWQmwcqgAhr+Mn6+Y02Gj02+qZrdlTKBQyJjxj69Dlt25l7tJOoDIWrrrd7U5s4ZVr/ggH5D3pXvd6mLTNxXXsXgmGTpDTJZUF5FmN1wGB8fixFls2lHBlIgVo4nXHRe1D/cQ6oO7kbaMZLW+/sWn+Aw61B+1JN8HfeIH1APmopETbUV6MOwX+rGNHNd7uOV31JShi2vFA08x9l3Way8/cnPrIQjzzdmxqwImolAzI8yEls/pWva3k6R6jFu2gRKRAUdsXFJOFeNhq6Zp5QU38Fy7kouAXRwm6Jb6B6YyyC/hve1G0Y9ZlCVBGFCr55aXpWvTY3oVCXKP+LcbjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
