travis:
  secure:
    BINSTAR_TOKEN: MNmpEDjHByy+8VCs6E6xDZsdnkq3LSUYaccycXD9W0cL9Yup5KTwNWF/yUBXaJXta5FKhTHfOFlD5amOuDUBrh/uZGlp7P702yMGdeQds22szMEiiEGWT6zF0aD32TCwIpYGnXE981qFXJamb+GnFMpVDmye028dZRW+21o3C6EjLd26Jvkguk6uPmi1k5jvNaCtEcdqA2d58xbf9dA4pxoune2X9/AT5c0FCXwlxLe1n7mwnmbzT2St16NkA6UDpOsJ8tT+BmffCtgeBFVQWeMJQdN6F7E/5f8qjSoGOx7MN9Qh6m/yIgHnv5E+M8Q9BJ3oL6Jh/ER0jxYwPiTm4ElzrVXXBbxiJD0QUGF7Pvf9LmFdGXLq5gXW+zvDqBYaKIk+1GxTXtuEhFfhWEsfCcHi2+DKfkk5cy0kLdc5MEuCzBkLQEdNS5C7jIFSwfHD9zJH1VowO9q1+veU67FjlYclTiapyIch7CoAduuPsMywQ9Z82OdgSa8X9RVPHI/BLij/Q2dOnIzLWx0q7Elvgx2RdvYZVNrYvLxO/+jQf/DN4k9d6ufofIu6ATvAadKIkqJY4cqZnBZu/4r3skPJtJRx7opmeLz28yhEzzwzQa5vx8sb66ec6MS/gvLzZnuhcw436xGI256wP9GCIElKO6X3eogfRjgzsKKYOqWc/Is=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
